USE MyTomilloCursos;

INSERT INTO GENEROS (genero) VALUES ('MASCULINO');
INSERT INTO GENEROS (genero) VALUES ('FEMENINO');
INSERT INTO GENEROS (genero) VALUES ('NO BINARIO');
INSERT INTO GENEROS (genero) VALUES ('PREFIERO NO ESPECIFICAR');
INSERT INTO GENEROS (genero) VALUES ('OTRO');

SELECT * FROM GENEROS;


INSERT INTO CAUSAS_ELIMINACION (causa) VALUES ('LENGUAJE INAPROPIADO');

SELECT * FROM CAUSAS_ELIMINACION;
